name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  check-commit-message:
    name: Validate commit messages
    runs-on: ubuntu-latest
    steps:
      - name: Conventional commits specification validation
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z ]+\))?: [\w ]+$'
          flags: 'gm'
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          error: 'Commit message has to conform with the conventional commits specification (https://www.conventionalcommits.org/en/v1.0.0/)"'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
