name: Labeler
on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]

jobs:
  labeler:
    name: Add and check labels
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v1.5.1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}} # optional, default to '${{ github.token }}' 
